import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ordersRouter from "./orders";
import menuRouter from "./menu";
import occasionsRouter from "./occasions";
import storageRouter from "./storage";
import pushTokensRouter from "./push-tokens";
import bannersRouter from "./banners";
import revenueRouter from "./revenue";
import smsRouter from "./sms";
import combosRouter from "./combos";
import walletRouter from "./wallet";
import { hoursRouter } from "./hours";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import pinOtpRouter from "./pin-otp";
import ratingsRouter from "./ratings";
import driversRouter from "./drivers";
import textsRouter from "./texts";
import discountsRouter from "./discounts";
import appearanceRouter from "./appearance";
import deliveryZonesRouter from "./delivery-zones";
import dashboardAuthRouter from "./dashboard-auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(ordersRouter);
router.use(menuRouter);
router.use("/occasions", occasionsRouter);
router.use(storageRouter);
router.use(pushTokensRouter);
router.use(bannersRouter);
router.use(revenueRouter);
router.use(smsRouter);
router.use(combosRouter);
router.use("/wallet", walletRouter);
router.use(hoursRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(pinOtpRouter);
router.use(ratingsRouter);
router.use(driversRouter);
router.use(textsRouter);
router.use(discountsRouter);
router.use(appearanceRouter);
router.use(deliveryZonesRouter);
router.use(dashboardAuthRouter);

export default router;
